### ISSUE TITLE
Refresh button crashing with Thunar 1.7.2 & thunarx-3

### ISSUE THREAD

**Issue by althonos** [althonos/thunar-torrent-property#1]

**Comment by linxon** [comment]
bump

**Comment by althonos** [comment]
@linxon : I need to address the [compilation issues with GLib 2.62 before](https://bugzilla.xfce.org/show_bug.cgi?id=16257) before I can address that :smile:

**Comment by althonos** [comment]
Fixed by removing requirement for background thread while updating torrent status.
