### ISSUE TITLE
thunar<=1.8.9 support

### ISSUE THREAD

**Issue by linxon** [althonos/thunar-torrent-property#3]
do it works with `thunar-1.8.9` and `thunarx-3`?

![Selection_047](https://user-images.githubusercontent.com/8144644/70614361-715f7f00-1c1b-11ea-8499-31a210ab8918.jpg)

**Comment by althonos** [comment]
If you can get it to compile, it should work, although right now with #4 I'm not sure you'll get it to work.

**Comment by linxon** [comment]
>I'm not sure you'll get it to work.

it works for me. Thank you! :)
